CREATE VIEW public.ports_active WITH (security_barrier='false') AS
 SELECT ports.id,
    ports.element_id,
    ports.category_id,
    ports.short_description,
    ports.long_description,
    ports.version,
    ports.revision,
    ports.maintainer,
    ports.homepage,
    ports.master_sites,
    ports.extract_suffix,
    ports.package_exists,
    ports.depends_build,
    ports.depends_run,
    ports.last_commit_id,
    ports.found_in_index,
    ports.forbidden,
    ports.broken,
    ports.date_added,
    ports.categories,
    ports.deprecated,
    ports.ignore,
    ports.master_port,
    ports.latest_link,
    ports.depends_lib,
    ports.no_latest_link,
    ports.no_package,
    ports.package_name,
    ports.portepoch,
    ports.no_cdrom,
    ports.restricted,
    ports.expiration_date,
    ports.is_interactive,
    ports.only_for_archs,
    ports.not_for_archs,
    ports.status,
    ports.showconfig,
    ports.license,
    ports.fetch_depends,
    ports.extract_depends,
    ports.patch_depends,
    ports.uses,
    ports.pkgmessage,
    ports.distinfo,
    ports.license_restricted,
    ports.manual_package_build,
    ports.license_perms,
    element.name,
    categories.name AS category,
    ports.pkg_plist,
    ports.makefile,
    ports.conflicts,
    ports.conflicts_build,
    ports.conflicts_install
   FROM public.categories,
    public.ports,
    public.element
  WHERE ((element.status = 'A'::bpchar) AND (categories.id = ports.category_id) AND (ports.element_id = element.id));

CREATE VIEW public.ports_all AS
 SELECT ports.id,
    ports.element_id,
    ports.category_id,
    ports.short_description,
    ports.long_description,
    ports.version,
    ports.revision,
    ports.maintainer,
    ports.homepage,
    ports.master_sites,
    ports.extract_suffix,
    ports.package_exists,
    ports.depends_build,
    ports.depends_run,
    ports.last_commit_id,
    ports.found_in_index,
    ports.forbidden,
    ports.broken,
    ports.date_added,
    ports.categories,
    ports.deprecated,
    ports.ignore,
    ports.master_port,
    ports.latest_link,
    ports.depends_lib,
    ports.no_latest_link,
    ports.no_package,
    ports.package_name,
    ports.portepoch,
    ports.no_cdrom,
    ports.restricted,
    ports.expiration_date,
    ports.is_interactive,
    ports.only_for_archs,
    ports.not_for_archs,
    ports.status,
    ports.showconfig,
    ports.license,
    ports.fetch_depends,
    ports.extract_depends,
    ports.patch_depends,
    ports.uses,
    ports.pkgmessage,
    ports.distinfo,
    ports.license_restricted,
    ports.manual_package_build,
    ports.license_perms,
    element.name,
    categories.name AS category,
    ports.pkg_plist,
    ports.makefile,
    ports.conflicts,
    ports.conflicts_build,
    ports.conflicts_install
   FROM public.categories,
    public.ports,
    public.element
  WHERE ((categories.id = ports.category_id) AND (ports.element_id = element.id));




